apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: springboot-vs
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: /spring
      route:
        - destination:
            host: springboot-app
            port:
              number: 8080
