apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: zipkin-vs
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: /zipkin
      route:
        - destination:
            host: zipkin
            port:
              number: 9411
